config/routes.rb
PennStation::Engine.routes.draw do

  root :to => 'pages#index'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"

  resources :activities
  resources :users
  resources :analytics
  resources :calendars
  resources :calendar_subscriptions
  resources :events
  resources :form_submissions

  resources :folders do
    collection do
      get :images_for_imagepicker
    end
  end

  resources :image_picker, :only => [:index, :show]

  resources :media

  resources :pages do
    collection do
      get :reorder
    end
  end

  resources :password_resets
  resources :scheduled_events

  resources :sections do
    collection do
      get :reorder
    end

    resources :form_fields
  end

  resources :sessions

  resources :slides do
    collection do
      get :images_for_imagepicker
    end
  end

  resources :slideshows
  resources :uploaded_files

end

app/models/penn_station/account.rb
# http://asciicasts.com/episodes/270-authentication-in-rails-3-1

module PennStation
  class Account < ActiveRecord::Base
    has_secure_password

    validates :email, presence: true,
                      uniqueness: true

    validates :name, :presence => true,
                     :uniqueness => true

    validates :password, :length => { :minimum => 8, :if => :validate_password? },
                         :confirmation => { :if => :validate_password? }

    validates :password_confirmation, :length => { :minimum => 8, :if => :validate_password? }

    before_create { generate_token(:auth_token) }
    before_validation :generate_random_password, :on => :create

    def activity_info
      "account #{name}"
    end

    def send_password_reset(mailer=UserMailer)
      generate_token(:password_reset_token)
      self.password_reset_sent_at = Time.zone.now
      save!
      mailer.password_reset(self).deliver#_later
    end

    def generate_token(column)
      begin
        self[column] = SecureRandom.urlsafe_base64
      end while Account.exists?(column => self[column])
    end

    private

    def generate_random_password
      self.password = self.password_confirmation = (0...8).map { (65 + rand(26)).chr }.join
    end

    def validate_password?
      !password.nil? || !password_confirmation.nil?
    end
  end
end

app/models/penn_station/activity.rb
module PennStation
  class Activity < ActiveRecord::Base
    validates :user, presence: true
    validates :info, presence: true
    validates :operation, presence: true

    def message
      "#{user} #{operation} #{info}"
    end
  end
end

app/models/penn_station/address.rb
module PennStation
  class Address < ActiveRecord::Base
    validates :address1, presence: true
    validates :city,     presence: true
    validates :state,    presence: true
    validates :zipcode,  presence: true

    def activity_info
      "address #{address1}"
    end
  end
end

app/models/penn_station/analytics_setting.rb
module PennStation
  class AnalyticsSetting < ActiveRecord::Base

    # Analytics Module information
    #
    # Module is registered at google cloud console for access only to Google Analytics API.
    #
    # GEMS
    # oauth2, https://github.com/intridea/oauth2, provides oauth2 authorization layer
    # legato, https://github.com/tpitale/legato, provides google analytics api v3 layer
    #
    #
    # OAUTH2
    # We use the Google Oauth2 "Installed Apps" flow. Normally used for desktop applications, but recommended
    # for content management system plugins.
    #
    # Basic flow:
    # 1. generate authorization url based on app's client id
    # 2. user visits authorization url and is prompted to authorize access for our app
    # 3. when user accepts, google generates authorization code
    # 4. user copies authorization code and submits it to app
    # 5. app uses authorization code to obtain access token and refresh token
    # 6. app uses access token to retrieve user analytics data. when access token expires, app uses
    #    refresh token to request new access token
    #
    # See https://developers.google.com/analytics/devguides/reporting/core/v3/gdataAuthorization#common_oauth
    #
    #
    # GOOGLE ANALYTICS API
    # See https://developers.google.com/analytics/devguides/reporting/core/v3/
    # and https://developers.google.com/analytics/devguides/config/mgmt/v3/
    #
    #
    # HIERARCHY OF ACCOUNTS, PROPERTIES, AND VIEWS (FORMERLY KNOWN AS PROFILES)
    # owner
    #   analytics account
    #   ...
    #   analytics account
    #     property <==> domain1.com <==> UA-XXXXXXXX-01
    #     ...
    #     property <==> domain5.com <==> UA-XXXXXXXX-05
    #       view1 = usually all analytics stats
    #       view2 = customized analytics stats
    #       view3 = customized analytics stats
    #       ...
    #
    # See https://support.google.com/analytics/answer/1009618?hl=en&ref_topic=1102143&rd=1
    #

    # CCTS PS Analytics Module app info, from google cloud console https://cloud.google.com/console‎
    OAUTH_CLIENT_ID = "309649842280-svjb0s5v36iajuklrvmcr42o65cetbtg.apps.googleusercontent.com"
    OAUTH_CLIENT_SECRET = "PAaUIRQu9R3zVELblDSnmlcS"
  end
end

app/models/penn_station/calendar.rb
module PennStation
  class Calendar < ActiveRecord::Base
    validates :name, presence: true, uniqueness: true

    has_and_belongs_to_many :scheduled_events,
                            class_name: "::PennStation::ScheduledEvent"

    def activity_info
      "calendar #{name}"
    end
  end
end

app/models/penn_station/event.rb
module PennStation
  class Event < ActiveRecord::Base
    validates :description, presence: true
    validates :name, presence: true
    validates :summary, presence: true

    has_many :scheduled_events, class_name: "::PennStation::ScheduledEvent"
    has_many :locations

    accepts_nested_attributes_for :locations
    accepts_nested_attributes_for :scheduled_events

    def has_calendar?(calendar)
      scheduled_events.map{|m| m.calendars.map{|m2| m2.name}}.flatten.include?(calendar.name)
    end

    def activity_info
      "event #{name}"
    end
  end
end

app/models/penn_station/folder.rb
module PennStation
  class Folder < ActiveRecord::Base
    validates :name, presence: true,
                     uniqueness: true

    has_many  :uploaded_files

    around_update :rename_media_folder_if_name_change

    def activity_info
      "folder #{name}"
    end

    private

    def rename_media_folder_if_name_change
      yield

      if name_changed?
        folders_dir = 'public/penn_station/folders'

        if File.exist? "#{folders_dir}/#{name_change[0]}"
          File.rename "#{folders_dir}/#{name_change[0]}", "#{folders_dir}/#{name_change[1]}"
        end
      end
    end
  end
end

app/models/penn_station/form_submission.rb
module PennStation
  class FormSubmission < ActiveRecord::Base
    attr_accessor :field_validations, :recipients

    def fields_valid?(security_question_correct)
      unless security_question_correct
        errors.add :security_question, "is incorrect."
      end

      field_validations.keys.each do |f|
        next unless %w( presence ).include?(field_validations[f])

        unless self.send("get_#{f}").present?
          errors.add f.to_sym, "cannot be empty."
        end
      end

      errors.empty?
    end

    def activity_info
      "form submission #{id}"
    end

    def method_missing(meth, *args, &block)
      if meth.to_s == 'recipients'
        JSON.parse(submitted_values).fetch('recipients', 'NO.RECIPIENTS@test.com')
      else
        (meth.to_s =~ /^get_(.+)$/) ? JSON.parse(submitted_values).fetch($1, '???') : super
      end
    end
  end
end

app/models/penn_station/form_submission_factory.rb
module PennStation
  class FormSubmissionFactory
    def initialize(page, values)
      @page, @values = page, values
    end

    def build
      FormSubmission.new(
        recipients: form_fields['recipients'],
        submitted_values: map_form_values.to_json,
        field_validations: form_validations
      )
    end

    private

    def map_form_values
      form_value_names.inject({}) do |obj, field|
        obj.merge({ field => @values['form_submission'].fetch(field, '') })
      end
    end

    def form_value_names
      form_fields['fields'].map{|h| h['input_name'] }
    end

    def form_validations
      form_fields['fields'].inject({}) do |obj, field|
        obj.merge({ field['input_name'] => field['input_validation'] })
      end
    end

    def form_fields
      form_section = @page.sections.find_by_stype(@values['form_submission']['stype'])
      form_section ? JSON.parse(form_section.content) : Hash.new( 'recipients' => 'NO.RECIPIENTS@test.com', 'fields' => [] )
    end
  end
end

app/models/penn_station/frontend/search.rb
class Search < ActiveRecord::Base
  def self.results(search_term, search_protected_pages = false)
    @results = {}

    pages = PennStation::Page.arel_table
    sections = PennStation::Section.arel_table

    @results[:pages] = PennStation::Page.joins(:sections)
      .where(pages[:published].eq(true))
      .where(pages[:url].does_not_match(PennStation::PROTECTED_PAGES))
      .where(sections[:content].matches("%#{search_term}%"))
      .uniq.to_a

    if defined?(PennStationBlog)
      posts = PennStationBlog::Post.arel_table

      @results[:blog_posts] = PennStationBlog::Post
        .where(posts[:publish].eq(true))
        .where(["title LIKE ? OR summary LIKE ? OR body LIKE ?",
               "%#{search_term}%", "%#{search_term}%", "%#{search_term}%"])
        .to_a
    end

    if search_protected_pages && PennStation::PROTECTED_PAGES.present?
      @results[:pages] += PennStation::Page.joins(:sections)
        .where(pages[:published].eq(true))
        .where(sections[:content].matches("%#{search_term}%"))
        .where(pages[:url].matches(PennStation::PROTECTED_PAGES))
        .uniq.to_a
    end

    @results
  end
end

app/models/penn_station/location.rb
module PennStation
  class Location < ActiveRecord::Base
    belongs_to :event, class_name: "::PennStation::Event"
    belongs_to :address, class_name: "::PennStation::Address"

    accepts_nested_attributes_for :address
  end
end

app/models/penn_station/media.rb
module PennStation
  class Media
    def self.all
      Folder.all.order(:name).includes(:uploaded_files) +
      Slideshow.all.order(:name).includes(:slides)
    end
  end
end

app/models/penn_station/nav_tree.rb
require 'rubytree'

module PennStation
  class NavTree < PageTree
    private

    def create_nodes
      Page.where("url != '/'").where(published: true, show_in_nav: true).order(:url).each do |page|
        add_page(page)
      end
    end
  end
end

app/models/penn_station/page.rb
module PennStation
  class Page < ActiveRecord::Base
    attr_accessor :parent_url

    validates :position, presence: true,
                         numericality: { :greater_than_or_equal_to => 0 }

    validates :ptype, format: { :with => /\A[a-zA-Z\d]+\z/ }

    validates :published, inclusion: { :in => [true, false] }

    validates :seo_description, :length => { :maximum => 155 }

    validates :show_in_nav, inclusion: { :in => [true, false] }

    validates :title, presence: true,
                      uniqueness: true

    validates :url, presence: true,
                    uniqueness: true

    before_validation :urlize

    before_validation :set_defaults, :on => :create

    after_find do |page|
      if ptype == 'HomePage'
        self.parent_url = ''
      else
        parent = url.split('/')[0..-2].join('/')
        parent = '/' if parent.empty?
        self.parent_url = parent
      end
    end

    has_many :sections, :dependent => :destroy

    scope :with_password_protection, -> { where(password_protected: true) }

    def self.lookup(url)
      self.find_by_url((url == '/') ? '/' : "/#{url}")
    end

    def self.top_level(page)
      return page if page.parent_url == '/' or page.url == '/'
      self.where(url: '/' + page.url.split('/')[1]).first
    end

    def parent
      Page.find_by_url(parent_url)
    end

    def home_page?
      url == '/'
    end

    def has_parent?
      not parent_url.empty?
    end

    def activity_info
      "page #{title}"
    end

    def portal(page=self)
      return nil unless page.present?
      return page if page.password_protected?
      portal(page.parent)
    end

    private

    def urlize
      if (ptype == 'HomePage')
        self.url = '/'
      else
        self.url = (parent_url || '/')
        self.url += '/' unless url[-1] == '/'
        self.url += (title || '').gsub(/ /, "_").gsub(/[^\d\w\-_]/, "").downcase
      end
    end

    def set_defaults
      self.ptype = ptype || (home_page?  ? 'HomePage' : 'Page')
      self.published = published || false
      self.published = true if home_page?
      self.show_in_nav = show_in_nav || true
      self.show_share_widget = show_share_widget || false
      self.sections << Section.new
      self.position = position || 0
      self.password_protected = password_protected || false

      true
    end
  end
end

app/models/penn_station/page_tree.rb
require 'rubytree'

module PennStation
  class PageTree < Tree::TreeNode
    def initialize(name = '/', page = Page.lookup('/'))
      super(name, page)
    end

    def build
      create_nodes
      sort_nodes
      self
    end

    private

    def create_nodes
      Page.where("url != '/'").order(:url).each do |page|
        add_page(page)
      end
    end

    def sort_nodes(node=self)
      child_list(node).sort!{|a,b| a.content.position <=> b.content.position }.each do |sorted_child|
        node << sorted_child
        sort_nodes(sorted_child)
      end
    end

    def child_list(node)
      node.children.map {|child| node.remove!(child) }
    end

    def add_page(page)
      url_components(page).inject(self) do |node, url_component|
        find_or_create(node, url_component, page)
      end
    end

    def url_components(page)
      page.url.split('/').reject{|e| e.empty? }
    end

    def find_or_create(node, name, page)
      begin
        node << PennStation::PageTree.new(name, page)
      rescue
        nil
      end

      node[name]
    end
  end
end

app/models/penn_station/role.rb
module PennStation
  class Role < ActiveRecord::Base

    LIST = [ "editor", "admin", "pennstation_admin" ]

    validates_associated :user

    validates :name, presence: true,
                     inclusion: { :in => LIST }

    belongs_to :user

    def self.available
      LIST
    end

    def assignable_roles(admin)

        # order matters here - most powerful to least powerful

      return LIST if admin.roles.map(&:name).include?("pennstation_admin")
      return [ "editor", "admin" ] if admin.roles.map(&:name).include?("admin")
      []
    end
  end
end

app/models/penn_station/scheduled_event.rb
module PennStation
  class ScheduledEvent < ActiveRecord::Base
    has_and_belongs_to_many :calendars, class_name: "::PennStation::Calendar"
    belongs_to              :event,     class_name: "::PennStation::Event"

    accepts_nested_attributes_for :calendars

    scope :next, -> (num) { where('ends_at > ?', Date.yesterday).order(:starts_at).limit(num) }

    def status
      return 'Upcoming' if starts_at > Date.today
      return 'Closed' if ends_at < Date.today
      'Current'
    end
  end
end

app/models/penn_station/slide.rb
require 'file_size_validator'

module PennStation
  class Slide < ActiveRecord::Base
    mount_uploader :image, SlideUploader

    validates :title, presence: true
    validates :image, presence: true,
                      file_size: { :maximum => SLIDE_MAX_SIZE }

    belongs_to  :slideshow

    before_save :update_file_attributes

    def activity_info
      "uploaded image to slideshow #{slideshow.name}"
    end

    private

    def update_file_attributes
      if image.present? && image_changed?
        self.content_type = image.file.content_type
        self.size = image.file.size
      end
    end
  end
end

app/models/penn_station/slideshow.rb
module PennStation
  class Slideshow < ActiveRecord::Base
    validates :name, presence: true,
                     uniqueness: true

    has_many :slides, -> { order 'position' }

    def activity_info
      "slideshow #{name}"
    end
  end
end

app/views/penn_station/folders/_form.html.erb
<%= form_for folder do |f| %>
  <% if folder.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in folder.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.has_role?("pennstation_admin") %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, :autofocus => (folder.new_record?) ? true : false %>
    </div>

    <div class="actions"><%= f.submit 'Save' %></div>
  <% end %>

<% end %>

<% unless folder.new_record? %>
  <form action="/admin/uploaded_files?folder_id=<%= @folder.name %>" class="dropzone" style="border: 2px solid black; min-height: 200px;">
    <div class="dz-default dz-message"><span>Drag-and-drop files here to upload, or click to browse files</span></div>
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
  </form>

  <ol class="uploaded_files_gallery">
    <% folder.uploaded_files.each do |fname| %>
        <li>
          <% if fname.content_type.include? 'image' %>
            <a href="<%= fname.file.to_s %>" target="_blank"><img src="<%= fname.file.url(:tiny) %>"/></a>
          <% else %>
            <a href="<%= fname.file.to_s %>" target="_blank"><%= File.basename(fname.file.to_s) %></a>
          <% end %>
          <%= link_to "Delete", fname, method: :delete, data: { confirm: 'Are you sure?' }, class: "obj_delete"  %>
          <%= link_to "Edit", edit_uploaded_file_path(fname), class: "obj_edit"  %>
        </li>
    <% end %>
  </ol>
<% end %>

app/views/penn_station/folders/edit.html.erb
<% content_for :toolbar_links do %>
  <ol class="row">
    <li><%= link_to "Back to all media", media_path, class: "button delete_button" %></li>
    <li><%= link_to "Delete this folder", @folder, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
  </ol>
<% end %>

<div id="<%= controller.controller_name %>">
  <h1>Edit <%= @folder.name %></h1>
  <%= render(:partial => "penn_station/folders/form", :locals => {:folder => @folder}) %>
</div>

app/views/penn_station/folders/index.html.erb
<% content_for :toolbar_links do %>
  <ol class="row">
    <li><%= link_to "Add a new folder", new_folder_path %></li>
  </ol>
<% end %>

<h1>Manage media</h1>

<ol id="<%= controller.controller_name %>_index" class="index">
  <li class="title-row row">
    <ol class="">
      <li class="name">Name</li>
      <li class="count">Number of Files</li>
    </ol>
  </li>

  <% @folders.each do |folder| %>
    <li id="<%= folder.id %>" class="row  <%= cycle("even", "odd") -%>">
      <ol class="cols">
        <li class="name"><a href="<%= edit_folder_path(folder) %>"><%= folder.name %> <%= image_tag("edit.png") %></a></li>
        <li class="count"><%= folder.uploaded_files.count %></li>
      </ol>
    </li>
  <% end %>
</ol>

app/views/penn_station/folders/index.js.erb
<% if @folders.empty? %>
<p>There are currently no uploaded files in the CMS</p>
<% else %>
<ul>
  <% @folders.each do |folder| %>
  <li class="file-folder"><%= folder.name %>
      <%= content_tag :ul, folder.uploaded_files.map {|file| content_tag :li, link_to(File.basename(file.file.to_s), file.file.to_s, :class => '')}.join.html_safe %>
  </li>
  <% end %>
</ul>

<script type="text/javascript">
$('#uploaded_file_list a').each(function(idx, link){
  var href = link.href.replace(window.location.protocol + '//' + window.location.host,'');
  if($('#uploaded_file_href').val() == href) $(link).addClass('current');
  $(link).click(function(e){
    $('#uploaded_file_href').val(href);
    $('#uploaded_file_list a').removeClass('current');
    $(this).addClass('current');
    return false; // equivalent to e.preventDefault() + e.stopPropagation()
  });
});

<% end %>

app/views/penn_station/folders/new.html.erb
<% content_for :toolbar_links do %>
  <ol class="row">
    <li><%= link_to "Back to all media", media_path, class: "button delete_button" %></li>
  </ol>
<% end %>

<h1>Create a new folder</h1>
<%= render(:partial => "penn_station/folders/form", :locals => {:folder => @folder}) %>

app/views/penn_station/folders/show.html.erb
<% content_for :toolbar_links do %>
  <ol class="row">
    <li><%= link_to "Back to all media", media_path, class: "button delete_button" %></li>
    <li><%= link_to "Delete this folder", @folder, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
  </ul>
<% end %>

<div id="<%= controller.controller_name %>">
  <h1>Show <%= @folder.name %></h1>
  <%= render(:partial => "penn_station/folders/form", :locals => {:folder => @folder}) %>
</div>